import { EquipableType } from "./data/model/itemType"

export const upper= new EquipableType("upper", "Head")
export const middle = new EquipableType("middle", "Head")
export const lower= new EquipableType("lower", "Head")
export const armor= new EquipableType("armor", "Body") 
export const rWeapon= new EquipableType("rWeapon", "R-hand")
export const lWeapon= new EquipableType("lWeapon", "L-hand")
export const garment= new EquipableType("garment", "Robe")
export const shoes = new EquipableType("shoes", "Shoes")
export const rAccessery = new EquipableType("rAccessery", "Accessery")
export const lAccessery = new EquipableType("lAccessery", "Accessery")

export const upperCostume= new EquipableType("upperCostume", "Head")
export const middleCostume = new EquipableType("middleCostume", "Head")
export const lowerCostume= new EquipableType("lowerCostume", "Head")
export const armorShadow= new EquipableType("armorShadow", "Body") 
export const weaponShadow= new EquipableType("weaponShadow", "Weapon")
export const sheidShadow= new EquipableType("sheidShadow", "Sheid")
export const garmentCostume= new EquipableType("garmentCostume", "Garment")
export const shoesShadow = new EquipableType("shoesShadow", "Shoes")
export const earringShadow = new EquipableType("earringShadow", "Earring")
export const pendantShadow = new EquipableType("pendantShadow", "Pendant")